version: '3'

networks:
  local:
    driver: bridge
    ipam:
      driver: default
      config:
         - subnet: 172.20.1.0/24

services:
  user1:
    build: ./Intranet/employé1
    networks:
      local:
        ipv4_address: 172.20.1.7
    tty: true
    container_name: user1
    hostname: user1
    dns: 172.20.1.2

  user2:
    build: ./Intranet/employé2
    networks:
      local:
        ipv4_address: 172.20.1.8
    tty: true
    container_name: user2
    hostname: user2
    dns: 172.20.1.2

  resolver:
    build: ./Intranet/resolver
    networks:
      local:
        ipv4_address: 172.20.1.2
    tty: true
    container_name: resolver
    hostname: resolver
    dns: 172.20.1.2

  soa:
    build: ./Intranet/soa
    networks:
      local:
        ipv4_address: 172.20.1.3
    tty: true
    container_name: soa
    hostname: soa 
    dns: 172.20.1.2

  web:
    build: ./Intranet/web
    networks:
      local:
        ipv4_address: 172.20.1.4
    tty: true
    container_name: web
    hostname: web
    dns: 172.20.1.2
    depends_on: db


  mail:
    build: ./Intranet/mail
    networks:
      local:
        ipv4_address: 172.20.1.5
    tty: true
    container_name: mail
    hostname: mail 
    dns: 172.20.1.2
    ports: 
      - "25:25"
      - "110:110"
      - "465:465"
      - "143:143"
      - "993:993"
    environment: 
      - maildomain=woodytoys.lab

#  db:
#    build: ./db
#    networks:
#      local:
#        ipv4_address: 192.168.0.7
#    tty: true
#    container_name: db
#    hostname: db 
#    dns: 192.168.0.3
