version: '3'

networks:
  local:
    driver: bridge
    ipam:
      driver: default
      config:
         - subnet: 172.20.1.0/24
  public:
    driver: bridge
    ipam:
        driver : default
        config:
         - subnet: 172.20.3.0/24

services:
  user1:
    build: ./Intranet/employé1
    networks:
      local:
        ipv4_address: 172.20.1.7
    tty: true
    container_name: user1
    hostname: user1
    dns: 172.20.1.2

  user2:
    build: ./Intranet/employé2
    networks:
      local:
        ipv4_address: 172.20.1.8
    tty: true
    container_name: user2
    hostname: user2
    dns: 172.20.1.2

  resolver:
    build: ./Intranet/resolver
    networks:
      local:
        ipv4_address: 172.20.1.2
    tty: true
    container_name: resolver
    hostname: resolver
    dns: 172.20.1.2

  soa:
    build: ./Intranet/soa
    networks:
      local:
        ipv4_address: 172.20.1.3
    tty: true
    container_name: soa
    hostname: soa 
    dns: 172.20.1.2

  web:
    build: ./Intranet/web
    networks:
      local:
        ipv4_address: 172.20.1.4
    tty: true
    container_name: web
    hostname: web
    dns: 172.20.1.2
    depends_on: 
      - db


  mail:
    build: ./Intranet/mail
    networks:
      local:
        ipv4_address: 172.20.1.5
    tty: true
    container_name: mail
    hostname: mail 
    dns: 172.20.1.2
    ports: 
      - "25:25"
      - "110:110"
      - "465:465"
      - "143:143"
      - "993:993"
    environment: 
      - maildomain=woodytoys.lab

  db:
    build: ./Intranet/DB
    networks:
      local:
        ipv4_address: 172.20.1.6
    tty: true
    container_name: db
    hostname: db 
    dns: 172.20.1.2


  resolver_public:
    build: ./Public/resolver_public
    networks:
      public:
        ipv4_address: 172.20.3.2
    tty: true
    container_name: resolver_public
    hostname: resolver_public
    dns: 172.20.3.2

  soa_public:
    build: ./Public/ns
    networks:
      public:
        ipv4_address: 172.20.3.3
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    tty: true
    container_name: soa_public
    hostname: soa_public
    dns: 172.20.3.2

  #web_public:
  #  build: ./Public/web_public
  #  networks:
  #    public:
  #      ipv4_address: 172.20.3.4
  #  ports:
  #    - "80:80"
  #    - "443:443"
  #  tty: true
  #  container_name: web_public
  #  hostname: web_public
  #  dns: 172.20.3.2
  #  depends_on: 
  #    - db