version: '3'

networks:
  local:
    driver: bridge
    ipam:
      driver: default
      config:
         - subnet: 172.17.0.0/24

services:
  user1:
    build: ./user1
    networks:
      local:
        ipv4_address: 172.17.0.4
    tty: true
    container_name: user1
    hostname: user1
    dns: 172.17.0.2

  user2:
    build: ./user2
    networks:
      local:
        ipv4_address: 172.17.0.5
    tty: true
    container_name: user2
    hostname: user2
    dns: 172.17.0.2

  resolver:
    build: ./resolver
    networks:
      local:
        ipv4_address: 172.17.0.2
    tty: true
    container_name: resolver
    hostname: resolver
    dns: 172.17.0.2

  soa:
    build: ./soa
    networks:
      local:
        ipv4_address: 172.17.0.3
    tty: true
    container_name: soa
    hostname: soa 
